---
name: Build and Inspect a Python Package
description: Builds the current package using standard PyPA tooling, keeps it as artifacts, then performs checks on it.
author: Hynek Schlawack
branding:
  icon: package
  color: purple

inputs:
  path:
    description: Where to look for the Python package to inspect.
    required: false
    default: .

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: "**/tools.txt"

    - name: Create venv for tools
      run: python3.10 -m venv /tmp/baipp
      shell: bash

    - run: /tmp/baipp/bin/python -m pip install -r ${{ github.action_path }}/requirements/tools.txt
      shell: bash

    # Build SDist, then build wheel out of it.
    - run: /tmp/baipp/bin/python -m build
      shell: bash
      working-directory: ${{ inputs.path }}

    # Give user overview over what we've built.
    - run: ls -l dist
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Upload built artifacts.
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: ${{ inputs.path }}/dist/*

    - run: /tmp/baipp/bin/check-wheel-contents dist/*.whl
      shell: bash
      working-directory: ${{ inputs.path }}

    - name: Check PyPI README
      shell: bash
      working-directory: ${{ inputs.path }}
      run: /tmp/baipp/bin/python -m twine check --strict dist/*

    - name: Show wheel & SDist contents hierarchically.
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        cd dist
        mkdir -p out/wheels
        /tmp/baipp/bin/python -m wheel unpack --dest out/wheels *.whl
        mkdir -p out/sdist
        tar xf *.tar.gz -C out/sdist
        tree -a out
