---
    name: CI w/ argon2-cffi-bindings

    on:
      push:
        branches: [main]
      pull_request:
        branches: [main]
      workflow_dispatch:

    env:
      FORCE_COLOR: "1" # Make tools pretty.
      SETUPTOOLS_SCM_PRETEND_VERSION: "1.0" # avoid warnings about shallow checkout

    jobs:
      check-argon2-cffi-bindings:
        name: Build & verify the argon2-cffi-bindings package.
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
            with:
              repository: hynek/argon2-cffi-bindings
              submodules: recursive
              path: hynek/argon2-cffi-bindings

          - uses: actions/checkout@v4
            with:
              path: action

          - uses: ./action
            id: baipp
            with:
              path: hynek/argon2-cffi-bindings
